#!/usr/bin/env bash

confirm() {
    read -r -p "${1:-Are you sure?} (y/N)" -n 1 response
    echo
    case "$response" in
        [yY])
            true
            ;;
        *)
            false
            ;;
    esac
}

INSTALL="pacaur -S --noconfirm --noedit"

if confirm "Install fish?"; then
    $INSTALL fish-git fzf
    curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher
    pip3 install --user virtualfish
fi

if confirm "Install neovim?"; then
    $INSTALL neovim python2-neovim python-neovim xsel
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
         https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if confirm "Install spacemacs?"; then
    $INSTALL emacs
    git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
fi

confirm "Install vscode?" && $INSTALL visual-studio-code
confirm "Install nerd fonts?" && $INSTALL wget nerd-fonts-complete
