#!/usr/bin/env bash

confirm() {
    read -r -p "${1:-Are you sure?} (y/N)" -n 1 response
    echo
    case "$response" in
        [yY])
            true
            ;;
        *)
            false
            ;;
    esac
}

INSTALL="pacaur -S --noconfirm --noedit"

confirm "Install fish?" && $INSTALL fish fisherman
confirm "Install virtualfish" && pip3 install --user virtualfish
confirm "Install neovim?" && $INSTALL neovim python2-neovim python-neovim xsel
confirm "Install vscode?" && $INSTALL visual-studio-code
confirm "Install nerd fonts?" && $INSTALL wget nerd-fonts-complete