#!/usr/bin/env bash

# Install essential managers (vim, node, go)
if [ -f "$HOME/.local/share/nvim/site/autoload/plug.vim" ]; then
    echo "Vim-plug - Vim plugin manager already installed - skipping"
else
    echo "Installing vim-plug - Vim plugin manager"
    curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ -d "$HOME/n" ]; then
    echo "N - Node version manager already installed - skipping"
else
    echo "Installing N - node version manager"
    curl -L https://git.io/n-install | bash -s -- -y -n -
    export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"
fi

if [ -d "$HOME/.gvm" ]; then
    echo "Gvm - Go version manager already installed - skipping"
else
    echo "Installing Gvm - Go version manager"
    zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
fi

# Install essential programs (neovim, zsh)
if command -v pacman > /dev/null 2>&1; then
    if ! command -v nvim > /dev/null 2>&1; then
        echo "Installing Neovim"

        sudo pacman --no-confirm -S neovim python2-neovim python-neovim
    else
        echo "Neovim already installed - skipping"
    fi

    if ! command -v zsh > /dev/null 2>&1; then
        echo "Installing Zsh"

        sudo pacman --no-confirm -S zsh
    else
        echo "Zsh already installed - skipping"
    fi
elif command -v apt-get > /dev/null 2>&1; then
    if ! command -v nvim > /dev/null 2>&1; then
        echo "Installing Neovim"

        sudo apt-get -y install software-properties-common
        sudo add-apt-repository -y ppa:neovim-ppa/stable
        sudo apt-get -y update
        sudo apt-get -y install neovim python-dev python-pip python3-dev python3-pip
        sudo pip2 install --upgrade pip
        sudo pip3 install --upgrade pip
        sudo pip2 install --upgrade neovim
        sudo pip3 install --upgrade neovim
    else
        echo "Neovim already installed - skipping"
    fi

    if ! command -v zsh > /dev/null 2>&1; then
        echo "Installing Zsh"

        sudo apt-get -y install zsh
    else
        echo "Zsh already installed - skipping"
    fi
else
    echo "Aborting installation! Operating system not supported!"
    exit 1
fi

