#!/usr/bin/env python

import socket
ip = socket.gethostbyname(socket.gethostname())

if ip == '192.168.2.27':
    print('%{F#8bbcd2}LTE%{F-}') 
elif ip == '192.168.2.28':
    print('%{F#d3cc8b}ADSL%{F-}')
else:
    print('%{F#a0d18a}DHCP%{F-}')
