#!/usr/bin/env python

import pyowm
import time

time.sleep(2)

owm = pyowm.OWM("04c5661a471dfc3a911c979b93af5056")

observation = owm.weather_at_place("Chelmiec,pl")
w = observation.get_weather()
temp = w.get_temperature("celsius")["temp"]

color_end="%{F-}"
color_temp=""
color_temps=["%{F#3675c1}", "%{F#2ba531}", "%{F#e2d42f}"]

icon_temps=["","",""]

if temp > 25:
    icon_temp=icon_temps[2]
    color_temp=color_temps[2]
elif temp > 15:
    icon_temp=icon_temps[1]
    color_temp=color_temps[1]
else:
    icon_temp=icon_temps[0]
    color_temp=color_temps[0]

output = "{}{}{}".format(color_temp,icon_temp,color_end)
output += "{}°".format(temp)

print(output)
