#!/usr/bin/env bash

icon="%{F#126a3d}%{F-}"

mpc | grep playing > /dev/null 2>&1

if [ $? -eq 0 ]; then
    metadata="$(mpc | head -1)"
    metadata=${metadata#*-}
    echo "$icon%{root.foreground}$metadata%{F-}"
else
    echo "$icon"
fi
