#!/usr/bin/env bash

icon=""

player_status=$(playerctl status 2> /dev/null)
if [[ $? -eq 0 ]]; then
    metadata="$(playerctl metadata artist) - $(playerctl metadata title)"
fi

if [[ $player_status = "Playing" ]]; then
    echo "%{F#aee8e6}$icon $metadata"
elif [[ $player_status = "Paused" ]]; then
    echo "%{F#65737e}$icon $metadata"
else
    echo "%{F#65737e}$icon"
fi
