#!/usr/bin/env bash

icon=""

mpc | grep playing > /dev/null 2>&1

if [ $? -eq 0 ]; then
    metadata="$(mpc | head -1)"
    metadata=${metadata#*-}
    echo "%{F#aee8e6}$icon $metadata%{F-}"
else
    echo "%{F#626853}$icon%{F-}"
fi
